title: Azure Elastic Jobs Manager
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://kr55.github.io/azure-elastic-jobs-client-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
