title: Azure Elastic Jobs Manager
description: Manage elastic jobs in Azure from your desktop.
theme: just-the-docs

url: https://elasticjobsmanager.azureops.org

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
