title: Azure Elastic Jobs Manager
description: Manage elastic jobs in Azure from your desktop.
theme: just-the-docs

url: https://elasticjobsmanager.azureops.org

aux_links:
  "Download Now":
    - "//github.com/just-the-docs/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

favicon_ico: "/assets/images/favicon.ico"
